feat(fixtures): fixtures data for customers
agritheory/test_utils pull request #39
Opened 2024-05-20 14:51 UTC by MyuddinKhatri

Issue - https://github.com/agritheory/test_utils/issues/10
Collected fixtures data for customers from Autoreader, beam, inventory_tools, electronic_payments

2024-05-20 14:53 UTC, MyuddinKhatri commented
@agritheory for tax_id under customer i have directly stores in fixtures instead of generating it randomly. Please let me know if I should keep this as it is change it to generate randomly.

2024-06-01 07:30 UTC, MyuddinKhatri commented
@agritheory should we add separate create_address() and create_contact() as both suppliers and customers have addresses?We can call create_suppliers, create_customers first then create_address and create_contact ?

2024-06-03 05:54 UTC, Alchez commented
@MyuddinKhatri I think it's better to just have the `create_suppliers` and `create_customers` commands create the downstream documents, since it seems less likely that an app would need just addresses or contacts.

2024-06-04 07:17 UTC, Alchez requested changes

2024-06-04 07:17 UTC, Alchez commented on test_utils/utils/setup_fixtures.py
> +				continue
If the user already exists and the JSON roles are updated to include `Customer`, should this also append that role before returning?

2024-06-04 07:17 UTC, Alchez commented on test_utils/utils/setup_fixtures.py
> +				continue
Similar to above. If links are added for a customer, should this also append a row for the link?

2024-06-04 07:17 UTC, Alchez commented on test_utils/utils/setup_fixtures.py
> +				continue
Same as contact.

2024-06-04 07:22 UTC, Alchez approved these changes

2024-06-04 14:13 UTC, agritheory commented
@MyuddinKhatri Can you rebase this to fix the pre-commit spelling issue?

2024-06-04 14:23 UTC, MyuddinKhatri commented
> @MyuddinKhatri Can you rebase this to fix the pre-commit spelling issue?

@agritheory codespell is complaining about `pheonix` Is this intentional?

2024-06-04 14:27 UTC, agritheory commented
> @agritheory codespell is complaining about pheonix Is this intentional?

No, let's change it to the most standard spelling. The number and variation of spellings of this particular word is wild. Here's an example that's local to me: 

![image](https://github.com/agritheory/test_utils/assets/18033666/ec82a700-b676-49d8-89ac-ba6fd10c9134)

2024-06-04 14:37 UTC, merged