feat(fixtures): fixtures data for employees
agritheory/test_utils pull request #52
Opened 2024-06-07 14:40 UTC by MyuddinKhatri

Issue  - https://github.com/agritheory/test_utils/issues/10
Collected fixtures for employee and their addresses from us_regional

2024-06-10 09:07 UTC, Alchez approved these changes

2024-06-10 14:16 UTC, agritheory commented on test_utils/utils/setup_fixtures.py
> +		empl.save()
@MyuddinKhatri says that we should make this company-sensitive. I propose this pattern:
```python
if settings.company:
     empl.company = settings.company
```

2024-06-10 14:17 UTC, agritheory requested changes
Make employee data company sensitive

2024-06-11 06:06 UTC, Alchez approved these changes

2024-06-21 13:11 UTC, merged