feat: setup company fixtures
agritheory/test_utils pull request #55
Opened 2024-06-16 07:32 UTC by MyuddinKhatri

Issue - #10 
Setup company fixtures for Companies - Ambrosia Pie Company, Chelsea Fruit Co, and Quincy Cloudberry Farm.

2024-06-18 06:11 UTC, Alchez approved these changes

2024-06-18 16:38 UTC, agritheory requested changes
A couple of tweaks here. I think we will have a bit of a "we won't know until we do the downstream work" problem here and that's OK.

2024-06-18 16:38 UTC, agritheory commented on test_utils/fixtures/setup.json
> +[
I think it's more appropriate to call this file `company.json`

2024-06-18 16:38 UTC, agritheory commented on test_utils/utils/setup_fixtures.py
> +	enable_all_roles_and_domains()
I think we want to remove both `enable_all_roles_and_domains()` and `set_defaults_for_tests()` - they don't really apply to how we do testing and if they're required we can handle it in the project(s).

2024-06-20 05:58 UTC, Alchez approved these changes

2024-06-20 13:03 UTC, agritheory commented on test_utils/utils/setup_fixtures.py
> +	frappe.db.commit()
This `commit` isn't required

2024-06-21 13:11 UTC, agritheory approved these changes

2024-06-21 13:11 UTC, merged